name: Go Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: local
      AWS_ACCESS_KEY_ID: "accessKey"
      AWS_SECRET_ACCESS_KEY: "secretKey"
      AWS_S3_ENDPOINT: "http://localhost:9000"
    services:
      minio:
        image: bitnami/minio
        env:
          MINIO_ROOT_USER: "accessKey"
          MINIO_ROOT_PASSWORD: "secretKey"
        ports:
          - 9000:9000
        options: --health-cmd="curl http://localhost:9000/minio/health/live"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: v2/go.mod
          cache-dependency-path: v2/go.sum

      - name: Test
        run: go test --modfile=v2/go.mod -v ./...
